[tool.black]
line-length = 100
target-version = ["py310"]
exclude = ["__pycache__"]

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true

[tool.flake8]
max-line-length = 100
ignore = ["E203", "W503"]
exclude = __pycache__,.venv
